import React,{useEffect,useMemo,useRef,useState}from'react';

const KEY='myWellness.preview.v2';
const AUTH='myWellness.previewSignedIn';
const DEF={profile:{name:'Lee',goal:1800,hashtag:'#HealthFirst'},foods:[],activities:[],fasting:[],menus:[]};
const STAGES=[['Blood Sugar Drop',4],['Fat Burning',12],['Ketosis',18],['Autophagy',24],['Deep Autophagy',48],['Growth Hormone Boost',72]];
const ACTS=[['Walking (brisk)',350],['Running (moderate)',600],['Walking (normal pace)',280],['Jogging (light)',450],['Walking (slow pace)',200],['Biking (leisure)',300]];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const dk=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const mins=(a,b)=>Math.max(0,Math.floor((new Date(b)-new Date(a))/60000));
const fmt=m=>{m=Math.max(0,Math.round(m));const h=Math.floor(m/60),r=m%60;return h?`${h}h ${r}m`:`${r}m`};
const load=()=>{try{return {...DEF,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return DEF}};
const Icon=({children})=><span className="i">{children}</span>;

function Modal({children,onClose,small=false}){return <div className="ov" onPointerDown={e=>e.target===e.currentTarget&&onClose?.()}><div className={`modal ${small?'small':''}`}>{onClose&&<button className="x" onClick={onClose}>×</button>}{children}</div></div>}
function Confirm({title,text,yes='Delete',danger=false,onYes,onNo}){return <Modal onClose={onNo} small><h2>{title}</h2><p className="muted">{text}</p><button className={`primary ${danger?'danger':''}`} onClick={onYes}>{yes}</button><button className="secondary" onClick={onNo}>Cancel</button></Modal>}
function Login({onIn}){const[e,setE]=useState(''),[p,setP]=useState('');return <div className="login"><div className="loginCard"><div className="brand">#SelfLove</div><h1>Welcome to #TheSelfLoveApp</h1><p>Sign in to continue</p><button className="google" onClick={()=>{localStorage.setItem(AUTH,'1');onIn()}}>G&nbsp;&nbsp; Continue with Google</button><div className="or">OR</div><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} placeholder="••••••••"/></label><button className="signin" onClick={()=>{localStorage.setItem(AUTH,'1');onIn()}}>Sign in</button><button className="link">Forgot password?</button></div></div>}

export default function TestApp(){
 const[user,setUser]=useState(localStorage.getItem(AUTH)==='1');const[state,setState]=useState(load);const[tab,setTab]=useState('cal');const[date,setDate]=useState(dk());const[modal,setModal]=useState(null);
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(state)),[state]);
 const active=state.fasting.find(x=>!x.end);const foods=state.foods.filter(x=>x.date===date);const acts=state.activities.filter(x=>x.date===date);const consumed=foods.reduce((a,b)=>a+(+b.cal||0),0);const burned=acts.reduce((a,b)=>a+(+b.cal||0),0);const left=(+state.profile.goal||1800)-consumed+burned;const pct=Math.max(0,Math.min(1,(consumed-burned)/Math.max(1,+state.profile.goal||1800)));
 const logs=useMemo(()=>[...foods.map(x=>({...x,kind:'food'})),...acts.map(x=>({...x,kind:'act'}))].sort((a,b)=>new Date(b.created)-new Date(a.created)),[foods,acts]);
 function up(fn){setState(s=>fn(s))}
 if(!user)return <Login onIn={()=>setUser(true)}/>;
 return <div className="app"><header><div><div className="hash">{state.profile.hashtag||'#HealthFirst'}</div><div className="hello">Good Morning, <b>{state.profile.name||'Lee'}</b></div></div><div className="headBtns"><button onClick={()=>setModal({t:'timer'})}>⏱</button><button onClick={()=>setModal({t:'settings'})}>⚙</button></div></header><main><div className="tabs"><button className={tab==='cal'?'on':''} onClick={()=>setTab('cal')}>Calories</button><button className={tab==='fast'?'on':''} onClick={()=>setTab('fast')}>Fasting{active&&<i/>}</button></div>{tab==='cal'?<Calories date={date} setDate={setDate} left={left} goal={state.profile.goal} consumed={consumed} burned={burned} pct={pct} logs={logs} setModal={setModal}/>:<Fasting state={state} active={active} up={up} setModal={setModal}/>}</main>{modal&&<Router modal={modal} close={()=>setModal(null)} state={state} up={up} date={date} setModal={setModal}/>}</div>
}

function Calories({date,setDate,left,goal,consumed,burned,pct,logs,setModal}){const[armed,setArmed]=useState(null);const timer=useRef(null);const shift=n=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);if(d<=new Date())setDate(dk(d))};return <><div className="dateNav"><button onClick={()=>shift(-1)}>‹</button><input type="date" value={date} max={dk()} onChange={e=>setDate(e.target.value)}/><button disabled={date>=dk()} onClick={()=>shift(1)}>›</button></div><div className="ring" style={{'--p':`${pct*360}deg`}}><div><b>{left}</b><span>calories left</span><small>Goal: {goal}</small></div></div><div className="stats"><div><b>{consumed}</b><span>CONSUMED</span></div><div><b>{burned}</b><span>BURNED</span></div></div><div className="actions"><button className="food" onClick={()=>setModal({t:'food'})}>＋ <span>FOOD</span></button><button className="act" onClick={()=>setModal({t:'activity'})}>＋ <span>ACTIVITY</span></button></div><h3>TODAY'S LOG</h3><div className="log">{!logs.length?<div className="empty">No entries yet today</div>:logs.map(x=><div className={`row ${armed===x.id?'armed':''}`} key={x.id} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left+r.width*.5)return;clearTimeout(timer.current);timer.current=setTimeout(()=>setArmed(x.id),520)}} onPointerUp={()=>clearTimeout(timer.current)} onPointerLeave={()=>clearTimeout(timer.current)}><Icon>{x.kind==='food'?'🍴':'🏃'}</Icon><b>{x.name}</b><strong>{x.kind==='food'?'+':'-'}{x.cal}</strong><div className="rowBtns"><button onClick={()=>setModal({t:'edit',item:x})}>✎</button><button className="trash" onClick={()=>setModal({t:'delLog',item:x})}>🗑</button></div></div>)}</div></>}

function Fasting({state,active,up,setModal}){const[,tick]=useState(0);useEffect(()=>{if(!active)return;const t=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(t)},[active]);const done=state.fasting.filter(x=>x.end),dur=done.map(x=>mins(x.start,x.end)),longest=dur.length?Math.max(...dur):0,total=dur.reduce((a,b)=>a+b,0),elapsed=active?mins(active.start,new Date()):0,next=STAGES.find(x=>elapsed<x[1]*60);return <div className="fastWrap">{active?<div className="fastCard activeFast"><span className="chip">{[...STAGES].reverse().find(x=>elapsed>=x[1]*60)?.[0]||'Fasting'}</span><div className="fastCircle"><b>{fmt(elapsed)}</b><span>{String(new Date().getSeconds()).padStart(2,'0')} sec</span></div>{next&&<div className="next"><b>Next: {next[0]}</b><span>{fmt(next[1]*60-elapsed)} to go</span></div>}<button className="stop" onClick={()=>setModal({t:'endFast',item:active})}>Stop Fasting</button></div>:<div className="fastCard ready"><h2>Ready to Fast?</h2><p>Start your fasting timer to track your progress.</p><button className="primary" onClick={()=>setModal({t:'startFast'})}>Start Fasting</button></div>}<div className="fastCard"><div className="fastStats"><div>🏆<b>{fmt(longest)}</b><span>Longest Fast</span></div><div>◷<b>{fmt(total)}</b><span>Total Fasting</span></div></div><h3>RECENT SESSIONS</h3>{!done.length?<div className="empty">No fasting sessions yet</div>:done.map(x=><div className="session" key={x.id}><span>◷</span><div><b>{fmt(mins(x.start,x.end))}</b><small>{new Date(x.start).toLocaleString()}</small></div><button className="trash" onClick={()=>setModal({t:'delFast',item:x})}>🗑</button></div>)}</div></div>}

function Router({modal,close,state,up,date,setModal}){if(modal.t==='food')return <Food state={state} up={up} date={date} close={close}/>;if(modal.t==='activity')return <Activity up={up} date={date} close={close} preset={modal.preset}/>;if(modal.t==='edit')return <Edit item={modal.item} up={up} close={close}/>;if(modal.t==='delLog')return <Confirm title="Delete Entry?" text={`Delete “${modal.item.name}”?`} danger onNo={close} onYes={()=>{up(s=>({...s,[modal.item.kind==='food'?'foods':'activities']:s[modal.item.kind==='food'?'foods':'activities'].filter(x=>x.id!==modal.item.id)}));close()}}/>;if(modal.t==='startFast')return <StartFast up={up} close={close}/>;if(modal.t==='endFast')return <EndFast item={modal.item} up={up} close={close}/>;if(modal.t==='delFast')return <Confirm title="Delete Fasting Session?" text={`Delete this ${fmt(mins(modal.item.start,modal.item.end))} fasting session?`} danger onNo={close} onYes={()=>{up(s=>({...s,fasting:s.fasting.filter(x=>x.id!==modal.item.id)}));close()}}/>;if(modal.t==='timer')return <Timer close={close} log={m=>setModal({t:'activity',preset:m})}/>;if(modal.t==='settings')return <Settings state={state} up={up} close={close}/>;return null}

function Food({state,up,date,close}){const[n,setN]=useState(''),[c,setC]=useState(''),[ask,setAsk]=useState(false),[pick,setPick]=useState(false);const save=menu=>{up(s=>({...s,foods:[{id:uid(),name:n.trim(),cal:+c,date,created:new Date().toISOString()},...s.foods],menus:menu&&!s.menus.some(x=>x.name.toLowerCase()===n.trim().toLowerCase())?[{id:uid(),name:n.trim(),cal:+c},...s.menus]:s.menus}));close()};if(ask)return <Modal small onClose={()=>setAsk(false)}><h2>Save to Menu?</h2><p className="muted">“{n}” is not in your saved menus. Save it for quick access later?</p><button className="primary" onClick={()=>save(true)}>Yes, save it</button><button className="secondary" onClick={()=>save(false)}>No, just log it</button></Modal>;if(pick)return <Modal onClose={()=>setPick(false)}><h2>Saved Menus</h2><div className="list">{state.menus.map(x=><button key={x.id} onClick={()=>{setN(x.name);setC(x.cal);setPick(false)}}><b>{x.name}</b><span>{x.cal} cal</span></button>)}</div></Modal>;return <Modal onClose={close}><h2>Log Food</h2><label>What did you eat?<button className="miniLink" onClick={()=>setPick(true)}>Menu</button><input value={n} onChange={e=>setN(e.target.value)} placeholder="e.g., Chicken Salad"/></label><label>Calories consumed<input inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,''))} placeholder="e.g., 350"/></label><button className="primary" onClick={()=>{if(!n.trim()||!+c)return;state.menus.some(x=>x.name.toLowerCase()===n.trim().toLowerCase())?save(false):setAsk(true)}}>Add Food Entry</button></Modal>}
function Activity({up,date,close,preset=30}){const[n,setN]=useState(''),[m,setM]=useState(String(preset||30)),[c,setC]=useState(''),[pick,setPick]=useState(false);if(pick)return <Modal onClose={()=>setPick(false)}><h2>Select Activity</h2><div className="list">{ACTS.map(x=><button key={x[0]} onClick={()=>{setN(x[0]);setC(Math.round(x[1]*(+m||0)/60));setPick(false)}}><b>{x[0]}</b><span>~{x[1]}/hr</span></button>)}</div></Modal>;return <Modal onClose={close}><h2>Log Activity</h2><label>What activity?<button className="miniLink" onClick={()=>setPick(true)}>Activities</button><input value={n} onChange={e=>setN(e.target.value)} placeholder="e.g., Walking"/></label><label>Duration (minutes)<input inputMode="numeric" value={m} onChange={e=>setM(e.target.value.replace(/\D/g,''))}/></label><label>Calories burned<input inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,''))} placeholder="e.g., 350"/></label><button className="primary green" onClick={()=>{if(!n.trim()||!+m||!+c)return;up(s=>({...s,activities:[{id:uid(),name:n.trim(),minutes:+m,cal:+c,date,created:new Date().toISOString()},...s.activities]}));close()}}>Add Activity</button></Modal>}
function Edit({item,up,close}){const[n,setN]=useState(item.name),[c,setC]=useState(String(item.cal));return <Modal onClose={close}><h2>Edit Entry</h2><label>Name<input value={n} onChange={e=>setN(e.target.value)}/></label><label>Calories<input inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,''))}/></label><button className="primary" onClick={()=>{up(s=>{const k=item.kind==='food'?'foods':'activities';return {...s,[k]:s[k].map(x=>x.id===item.id?{...x,name:n,cal:+c}:x)}});close()}}>Save Changes</button></Modal>}
function StartFast({up,close}){const now=new Date(),[date,setDate]=useState(dk(now)),[time,setTime]=useState(`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`);return <Modal onClose={close}><h2>Start Fasting</h2><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><button className="primary" onClick={()=>{up(s=>({...s,fasting:[{id:uid(),start:new Date(`${date}T${time}:00`).toISOString(),end:null},...s.fasting]}));close()}}>Start</button></Modal>}
function EndFast({item,up,close}){return <Confirm title="End Fasting Session?" text={`You've been fasting for ${fmt(mins(item.start,new Date()))}.`} yes="End Session" danger onNo={close} onYes={()=>{up(s=>({...s,fasting:s.fasting.map(x=>x.id===item.id?{...x,end:new Date().toISOString()}:x)}));close()}}/>}
function Timer({close,log}){const[h,setH]=useState('0'),[m,setM]=useState('0'),[s,setS]=useState('0'),[left,setLeft]=useState(0),[run,setRun]=useState(false),[end,setEnd]=useState(0),[total,setTotal]=useState(0);useEffect(()=>{if(!run)return;const t=setInterval(()=>{const r=Math.max(0,Math.ceil((end-Date.now())/1000));setLeft(r);if(!r){setRun(false);navigator.vibrate?.([180,80,300])}},250);return()=>clearInterval(t)},[run,end]);const base=(+h||0)*3600+(+m||0)*60+(+s||0),disp=left||base,txt=`${String(Math.floor(disp/3600)).padStart(2,'0')}:${String(Math.floor(disp%3600/60)).padStart(2,'0')}:${String(disp%60).padStart(2,'0')}`;return <Modal onClose={close} small><h2>Timer</h2><div className="timer">{txt}</div>{!total&&<div className="timerInputs"><input inputMode="numeric" value={h} onChange={e=>setH(e.target.value.replace(/\D/g,''))}/><input inputMode="numeric" value={m} onChange={e=>setM(e.target.value.replace(/\D/g,''))}/><input inputMode="numeric" value={s} onChange={e=>setS(e.target.value.replace(/\D/g,''))}/></div>}<button className="primary" onClick={()=>{if(run){setRun(false);return}const t=left||base;if(!t)return;setTotal(total||t);setLeft(t);setEnd(Date.now()+t*1000);setRun(true)}}>{run?'Pause':total?'Resume':'Start'}</button>{total&&!run&&<><button className="secondary" onClick={()=>{setLeft(0);setTotal(0)}}>Reset</button>{left===0&&<button className="primary green" onClick={()=>log(Math.max(1,Math.round(total/60)))}>Log as Activity</button>}</>}</Modal>}
function Settings({state,up,close}){const[p,setP]=useState({...state.profile});return <Modal onClose={close}><h2>Settings</h2><label>Name<input value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></label><label>Calorie Goal<input inputMode="numeric" value={p.goal} onChange={e=>setP({...p,goal:e.target.value.replace(/\D/g,'')})}/></label><label>Hashtag<input value={p.hashtag} onChange={e=>setP({...p,hashtag:e.target.value})}/></label><button className="primary" onClick={()=>{up(s=>({...s,profile:p}));close()}}>Save Settings</button></Modal>}
