import React,{useEffect,useMemo,useRef,useState}from'react';

const KEY='selfLove.preview.v3';
const AUTH='selfLove.previewSignedIn';
const TZ='Asia/Manila';
const DEFAULT_COLORS={background:'#22333b',primary:'#eae0d5',secondary:'#c6ac8f',tabBackground:'#d1f0b1',textPrimary:'#eae0d5',textSecondary:'#c6ac8f',progressBar:'#00f000',foodButton:'#943a1a',activityButton:'#2a722f'};
const DEFAULT_PROFILE={name:'Lee',heightCm:160,weightKg:83,dob:'1990-08-31',gender:'male',activityLevel:'sedentary',goal:1800,useSuggested:false,timezone:TZ,hashtagMode:'auto',manualHashtag:'#HealthFirst',colors:DEFAULT_COLORS};
const DEF={profile:DEFAULT_PROFILE,foods:[],activities:[],fasting:[],menus:[]};
const STAGES=[['Blood Sugar Drop',4,'Blood sugar levels begin to decrease'],['Fat Burning',12,'Body starts using fat for energy'],['Ketosis',18,'Liver produces ketones for brain fuel'],['Autophagy',24,'Cellular cleanup and regeneration begins'],['Deep Autophagy',48,'Extended fasting stage'],['Growth Hormone Boost',72,'Hormonal changes may occur during prolonged fasting']];
const ACTS=[['Walking (brisk)',350,'5.5–6.5 km/h'],['Running (moderate)',600,'8–10 km/h'],['Walking (normal pace)',280,'4–5 km/h'],['Jogging (light)',450,'6–8 km/h'],['Walking (slow pace)',200,'3–4 km/h'],['Biking (leisure)',300,'10–15 km/h']];
const HASHES=['#HealthFirst','#SelfCare','#StayActive','#MindfulDay','#BetterEveryDay','#ChooseWell','#SmallWins','#KeepGoing','#StrongToday','#LoveYourself','#MoveMore','#Balance','#Wellness','#BeKindToYou','#HealthyHabits','#Progress','#FeelGood','#DailyReset','#Nourish','#FocusOnYou','#StrongMind','#RestAndReset','#BePresent','#HealthyChoice','#GoodEnergy','#KeepMoving','#SelfLove','#DailyWellness','#BetterChoices','#OneDayAtATime','#YouFirst'];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const load=()=>{try{return {...DEF,...JSON.parse(localStorage.getItem(KEY)||'{}'),profile:{...DEFAULT_PROFILE,...JSON.parse(localStorage.getItem(KEY)||'{}').profile,colors:{...DEFAULT_COLORS,...JSON.parse(localStorage.getItem(KEY)||'{}').profile?.colors}}}catch{return DEF}};
const mins=(a,b=new Date())=>Math.max(0,Math.floor((new Date(b)-new Date(a))/60000));
const fmt=m=>{m=Math.max(0,Math.round(m));const h=Math.floor(m/60),r=m%60;return h?`${h}h ${r}m`:`${r}m`};
function manilaParts(d=new Date()){const f=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(d);const o={};f.forEach(x=>o[x.type]=x.value);return o}
const manilaKey=(d=new Date())=>{const p=manilaParts(d);return `${p.year}-${p.month}-${p.day}`};
const todayLabel=()=>{const p=manilaParts();return `${p.month}/${p.day}/${p.year}`};
const greeting=()=>{const h=+manilaParts().hour;return h<12?'Good Morning':h<18?'Good Afternoon':'Good Evening'};
const manilaNowLocal=()=>{const p=manilaParts();return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}+08:00`};
const age=dob=>{if(!dob)return 0;const now=manilaParts(),d=new Date(`${dob}T00:00:00+08:00`);let a=+now.year-d.getFullYear();if((+now.month-1<d.getMonth())||(+now.month-1===d.getMonth()&&+now.day<d.getDate()))a--;return a};
const bmr=p=>Math.round(10*(+p.weightKg||0)+6.25*(+p.heightCm||0)-5*age(p.dob)+(p.gender==='male'?5:-161));
const tdee=p=>Math.round(bmr(p)*({sedentary:1.2,light:1.375,moderate:1.55,very:1.725,extra:1.9}[p.activityLevel]||1.2));
const Icon=({children})=><span className="i">{children}</span>;

function Modal({children,onClose,small=false,wide=false}){return <div className="ov" onPointerDown={e=>e.target===e.currentTarget&&onClose?.()}><div className={`modal ${small?'small':''} ${wide?'wide':''}`}>{onClose&&<button className="x" onClick={onClose}>×</button>}{children}</div></div>}
function Confirm({title,text,yes='Delete',danger=false,onYes,onNo}){return <Modal onClose={onNo} small><h2>{title}</h2><p className="muted">{text}</p><button className={`primary ${danger?'danger':''}`} onClick={onYes}>{yes}</button><button className="secondary" onClick={onNo}>Cancel</button></Modal>}
function Login({onIn}){const[e,setE]=useState(''),[p,setP]=useState('');return <div className="login"><div className="loginCard"><div className="heartLogo">♡</div><h1>Welcome to SelfLove</h1><p>Sign in to continue</p><button className="google" onClick={()=>{localStorage.setItem(AUTH,'1');onIn()}}>G&nbsp;&nbsp; Continue with Google</button><div className="or">OR</div><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} placeholder="••••••••"/></label><button className="signin" onClick={()=>{localStorage.setItem(AUTH,'1');onIn()}}>Sign in</button></div></div>}

export default function TestAppV3(){
 const[user,setUser]=useState(localStorage.getItem(AUTH)==='1');const[state,setState]=useState(load);const[tab,setTab]=useState('cal');const[date,setDate]=useState(manilaKey());const[modal,setModal]=useState(null);
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(state)),[state]);
 useEffect(()=>{const sync=()=>document.documentElement.style.setProperty('--vvh',`${window.visualViewport?.height||window.innerHeight}px`);sync();window.visualViewport?.addEventListener('resize',sync);window.visualViewport?.addEventListener('scroll',sync);const focus=e=>setTimeout(()=>e.target?.scrollIntoView?.({block:'center',behavior:'smooth'}),120);document.addEventListener('focusin',focus);return()=>{window.visualViewport?.removeEventListener('resize',sync);window.visualViewport?.removeEventListener('scroll',sync);document.removeEventListener('focusin',focus)}},[]);
 const active=state.fasting.find(x=>!x.end);const foods=state.foods.filter(x=>x.date===date);const acts=state.activities.filter(x=>x.date===date);const consumed=foods.reduce((a,b)=>a+(+b.cal||0),0);const burned=acts.reduce((a,b)=>a+(+b.cal||0),0);const goal=state.profile.useSuggested?tdee(state.profile):(+state.profile.goal||1800);const left=goal-consumed+burned;const pct=Math.max(0,Math.min(1,(consumed-burned)/Math.max(1,goal)));
 const logs=useMemo(()=>[...foods.map(x=>({...x,kind:'food'})),...acts.map(x=>({...x,kind:'act'}))].sort((a,b)=>new Date(b.created)-new Date(a.created)),[foods,acts]);
 const hashtag=state.profile.hashtagMode==='manual'?state.profile.manualHashtag:HASHES[(+manilaParts().day-1)%HASHES.length];
 const colors={...DEFAULT_COLORS,...state.profile.colors};
 function up(fn){setState(s=>fn(s))}
 if(!user)return <Login onIn={()=>setUser(true)}/>;
 return <div className="app" style={{'--bg':colors.background,'--primary':colors.primary,'--secondary':colors.secondary,'--tab':colors.tabBackground,'--text1':colors.textPrimary,'--text2':colors.textSecondary,'--progress':colors.progressBar,'--food':colors.foodButton,'--activity':colors.activityButton}}><header><div><div className="hash">{hashtag}</div><div className="hello">{greeting()}, <b>{state.profile.name||'Lee'}</b></div></div><div className="headBtns"><button onClick={()=>setModal({t:'timer'})}>⏱</button><button onClick={()=>setModal({t:'settings'})}>⚙</button></div></header><main><div className="tabs"><button className={tab==='cal'?'on':''} onClick={()=>setTab('cal')}>Calories</button><button className={tab==='fast'?'on':''} onClick={()=>setTab('fast')}>Fasting{active&&<i/>}</button></div>{tab==='cal'?<Calories date={date} setDate={setDate} left={left} goal={goal} consumed={consumed} burned={burned} pct={pct} logs={logs} setModal={setModal}/>:<Fasting state={state} active={active} setModal={setModal}/>}</main>{modal&&<Router modal={modal} close={()=>setModal(null)} state={state} up={up} date={date} setModal={setModal}/>}</div>
}

function Calories({date,setDate,left,goal,consumed,burned,pct,logs,setModal}){const[armed,setArmed]=useState(null);const timer=useRef(null);const shift=n=>{const d=new Date(`${date}T12:00:00+08:00`);d.setUTCDate(d.getUTCDate()+n);const k=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);if(k<=manilaKey())setDate(k)};return <><div className="dateNav"><button onClick={()=>shift(-1)}>‹</button><label>{date===manilaKey()?`Today: ${todayLabel()}`:date}<input type="date" value={date} max={manilaKey()} onChange={e=>setDate(e.target.value)}/></label><button disabled={date>=manilaKey()} onClick={()=>shift(1)}>›</button></div><div className="ring" style={{'--p':`${pct*360}deg`}}><div><b>{left}</b><span>calories left</span><small>Goal: {goal}</small></div></div><div className="stats"><div><b>{consumed}</b><span>CONSUMED</span></div><div><b>{burned}</b><span>BURNED</span></div></div><div className="actions"><button className="food" onClick={()=>setModal({t:'food'})}>＋ <span>FOOD</span></button><button className="act" onClick={()=>setModal({t:'activity'})}>＋ <span>ACTIVITY</span></button></div><h3>TODAY'S LOG</h3><div className="log">{!logs.length?<div className="empty">No entries yet today</div>:logs.map(x=><div className={`row ${armed===x.id?'armed':''}`} key={x.id} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left+r.width*.5)return;clearTimeout(timer.current);timer.current=setTimeout(()=>setArmed(x.id),520)}} onPointerUp={()=>clearTimeout(timer.current)} onPointerLeave={()=>clearTimeout(timer.current)}><Icon>{x.kind==='food'?'🍴':'🏃'}</Icon><b>{x.name}</b><strong>{x.kind==='food'?'+':'-'}{x.cal}</strong><div className="rowBtns"><button onClick={()=>setModal({t:'edit',item:x})}>✎</button><button className="trash" onClick={()=>setModal({t:'delLog',item:x})}>🗑</button></div></div>)}</div></>}

function Fasting({state,active,setModal}){const[,tick]=useState(0);useEffect(()=>{if(!active)return;const t=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(t)},[active]);const done=state.fasting.filter(x=>x.end),dur=done.map(x=>mins(x.start,x.end)),longest=dur.length?Math.max(...dur):0,total=dur.reduce((a,b)=>a+b,0),elapsed=active?mins(active.start):0,elapsedH=elapsed/60,current=[...STAGES].reverse().find(x=>elapsedH>=x[1]),next=STAGES.find(x=>elapsedH<x[1]);return <div className="fastWrap">{active?<div className="fastCard activeFast"><span className="chip">{current?.[0]||'Fasting'}</span><div className="fastCircle"><b>{fmt(elapsed)}</b><span>{String(Math.floor((Date.now()-new Date(active.start))/1000)%60).padStart(2,'0')} sec</span></div>{next&&<div className="next"><b>Next: {next[0]}</b><span>{fmt(next[1]*60-elapsed)} to go</span><div className="miniProg"><i style={{width:`${Math.min(100,elapsedH/next[1]*100)}%`}}/></div></div>}<button className="stop" onClick={()=>setModal({t:'endFast',item:active})}>Stop Fasting</button></div>:<div className="fastCard ready"><h2>Ready to Fast?</h2><p>Start your fasting timer to track your progress through different fasting stages.</p><button className="primary" onClick={()=>setModal({t:'startFast'})}>Start Fasting</button></div>}<div className="fastCard stages"><h3>FASTING STAGES</h3>{STAGES.map(x=>{const doneStage=elapsedH>=x[1],isNext=next?.[1]===x[1];return <div className={`stage ${doneStage?'done':isNext?'nextStage':''}`} key={x[1]}><span>{doneStage?'✓':x[1]>=72?'💪':x[1]>=48?'🌌':'○'}</span><div><b>{x[0]}</b><small>{x[2]}</small></div><strong>{x[1]}h</strong></div>})}</div><div className="fastCard"><div className="fastStats"><div>🏆<b>{fmt(longest)}</b><span>Longest Fast</span></div><div>◷<b>{fmt(total)}</b><span>Total Fasting</span></div></div><h3>RECENT SESSIONS</h3>{!done.length?<div className="empty">No fasting sessions yet</div>:done.slice(0,8).map(x=><div className="session" key={x.id}><span>◷</span><div><b>{fmt(mins(x.start,x.end))}</b><small>{new Intl.DateTimeFormat('en-US',{timeZone:TZ,dateStyle:'medium',timeStyle:'short'}).format(new Date(x.start))}</small></div><button className="trash" onClick={()=>setModal({t:'delFast',item:x})}>🗑</button></div>)}</div></div>}

function Router({modal,close,state,up,date,setModal}){if(modal.t==='food')return <Food state={state} up={up} date={date} close={close}/>;if(modal.t==='activity')return <Activity up={up} date={date} close={close} preset={modal.preset}/>;if(modal.t==='edit')return <Edit item={modal.item} up={up} close={close}/>;if(modal.t==='delLog')return <Confirm title="Delete Entry?" text={`Delete “${modal.item.name}”?`} danger onNo={close} onYes={()=>{up(s=>({...s,[modal.item.kind==='food'?'foods':'activities']:s[modal.item.kind==='food'?'foods':'activities'].filter(x=>x.id!==modal.item.id)}));close()}}/>;if(modal.t==='startFast')return <StartFast up={up} close={close}/>;if(modal.t==='endFast')return <EndFast item={modal.item} up={up} close={close}/>;if(modal.t==='delFast')return <Confirm title="Delete Fasting Session?" text={`Delete this ${fmt(mins(modal.item.start,modal.item.end))} fasting session?`} danger onNo={close} onYes={()=>{up(s=>({...s,fasting:s.fasting.filter(x=>x.id!==modal.item.id)}));close()}}/>;if(modal.t==='timer')return <Timer close={close} log={m=>setModal({t:'activity',preset:m})}/>;if(modal.t==='settings')return <SettingsHome state={state} close={close} setModal={setModal}/>;if(modal.t==='profile')return <Profile state={state} up={up} setModal={setModal}/>;if(modal.t==='goal')return <Goal state={state} up={up} setModal={setModal}/>;if(modal.t==='timezone')return <Timezone state={state} up={up} setModal={setModal}/>;if(modal.t==='menus')return <Menus state={state} up={up} setModal={setModal}/>;if(modal.t==='hashtag')return <Hashtag state={state} up={up} setModal={setModal}/>;if(modal.t==='colors')return <Colors state={state} up={up} setModal={setModal}/>;return null}

function Food({state,up,date,close}){const[n,setN]=useState(''),[c,setC]=useState(''),[ask,setAsk]=useState(false),[pick,setPick]=useState(false);const save=menu=>{up(s=>({...s,foods:[{id:uid(),name:n.trim(),cal:+c,date,created:new Date().toISOString()},...s.foods],menus:menu&&!s.menus.some(x=>x.name.toLowerCase()===n.trim().toLowerCase())?[{id:uid(),name:n.trim(),cal:+c},...s.menus]:s.menus}));close()};if(ask)return <Modal small onClose={()=>setAsk(false)}><h2>Save to Menu?</h2><p className="muted">“{n}” is not in your saved menus. Save it for quick access later?</p><button className="primary" onClick={()=>save(true)}>Yes, save it</button><button className="secondary" onClick={()=>save(false)}>No, just log it</button></Modal>;if(pick)return <Modal onClose={()=>setPick(false)}><h2>Saved Menus</h2><div className="list">{state.menus.map(x=><button key={x.id} onClick={()=>{setN(x.name);setC(x.cal);setPick(false)}}><b>{x.name}</b><span>{x.cal} cal</span></button>)}</div></Modal>;return <Modal onClose={close}><h2>Log Food</h2><label>What did you eat?<button className="miniLink" onClick={()=>setPick(true)}>Menu</button><input value={n} onChange={e=>setN(e.target.value)} placeholder="e.g., Chicken Salad"/></label><label>Calories consumed<input inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,''))} placeholder="e.g., 350"/></label><button className="primary" onClick={()=>{if(!n.trim()||!+c)return;state.menus.some(x=>x.name.toLowerCase()===n.trim().toLowerCase())?save(false):setAsk(true)}}>Add Food Entry</button></Modal>}
function Activity({up,date,close,preset=30}){const[n,setN]=useState(''),[m,setM]=useState(String(preset||30)),[c,setC]=useState(''),[pick,setPick]=useState(false);if(pick)return <Modal onClose={()=>setPick(false)}><h2>Select Activity</h2><div className="list">{ACTS.map(x=><button key={x[0]} onClick={()=>{setN(x[0]);setC(Math.round(x[1]*(+m||0)/60));setPick(false)}}><div><b>{x[0]}</b><small>{x[2]}</small></div><span>~{x[1]}/hr</span></button>)}</div></Modal>;return <Modal onClose={close}><h2>Log Activity</h2><label>What activity?<button className="miniLink" onClick={()=>setPick(true)}>Activities</button><input value={n} onChange={e=>setN(e.target.value)} placeholder="e.g., Walking"/></label><label>Duration (minutes)<input inputMode="numeric" value={m} onChange={e=>setM(e.target.value.replace(/\D/g,''))}/></label><label>Calories burned<input inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,''))} placeholder="e.g., 350"/></label><button className="primary green" onClick={()=>{if(!n.trim()||!+m||!+c)return;up(s=>({...s,activities:[{id:uid(),name:n.trim(),minutes:+m,cal:+c,date,created:new Date().toISOString()},...s.activities]}));close()}}>Add Activity</button></Modal>}
function Edit({item,up,close}){const[n,setN]=useState(item.name),[c,setC]=useState(String(item.cal));return <Modal onClose={close}><h2>Edit Entry</h2><label>Name<input value={n} onChange={e=>setN(e.target.value)}/></label><label>Calories<input inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,''))}/></label><button className="primary" onClick={()=>{up(s=>{const k=item.kind==='food'?'foods':'activities';return {...s,[k]:s[k].map(x=>x.id===item.id?{...x,name:n,cal:+c}:x)}});close()}}>Save Changes</button></Modal>}
function StartFast({up,close}){const p=manilaParts(),[date,setDate]=useState(`${p.year}-${p.month}-${p.day}`),[time,setTime]=useState(`${p.hour}:${p.minute}`);return <Modal onClose={close}><h2>Start Fasting</h2><p className="muted">Default is the current Philippine time.</p><label>Date<input type="date" max={manilaKey()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><button className="primary" onClick={()=>{up(s=>({...s,fasting:[{id:uid(),start:new Date(`${date}T${time}:00+08:00`).toISOString(),end:null},...s.fasting]}));close()}}>Start</button></Modal>}
function EndFast({item,up,close}){return <Confirm title="End Fasting Session?" text={`You've been fasting for ${fmt(mins(item.start))}.`} yes="End Session" danger onNo={close} onYes={()=>{up(s=>({...s,fasting:s.fasting.map(x=>x.id===item.id?{...x,end:new Date().toISOString()}:x)}));close()}}/>}
function Timer({close,log}){const[h,setH]=useState('0'),[m,setM]=useState('0'),[s,setS]=useState('0'),[left,setLeft]=useState(0),[run,setRun]=useState(false),[end,setEnd]=useState(0),[total,setTotal]=useState(0);useEffect(()=>{if(!run)return;const t=setInterval(()=>{const r=Math.max(0,Math.ceil((end-Date.now())/1000));setLeft(r);if(!r){setRun(false);navigator.vibrate?.([180,80,300])}},250);return()=>clearInterval(t)},[run,end]);const base=(+h||0)*3600+(+m||0)*60+(+s||0),disp=left||base,txt=`${String(Math.floor(disp/3600)).padStart(2,'0')}:${String(Math.floor(disp%3600/60)).padStart(2,'0')}:${String(disp%60).padStart(2,'0')}`;return <Modal onClose={close} small><h2>Timer</h2><div className="timer">{txt}</div>{!total&&<div className="timerInputs"><input inputMode="numeric" value={h} onChange={e=>setH(e.target.value.replace(/\D/g,''))}/><input inputMode="numeric" value={m} onChange={e=>setM(e.target.value.replace(/\D/g,''))}/><input inputMode="numeric" value={s} onChange={e=>setS(e.target.value.replace(/\D/g,''))}/></div>}<button className="primary" onClick={()=>{if(run){setRun(false);return}const t=left||base;if(!t)return;setTotal(total||t);setLeft(t);setEnd(Date.now()+t*1000);setRun(true)}}>{run?'Pause':total?'Resume':'Start'}</button>{total&&!run&&<><button className="secondary" onClick={()=>{setLeft(0);setTotal(0)}}>Reset</button>{left===0&&<button className="primary green" onClick={()=>log(Math.max(1,Math.round(total/60)))}>Log as Activity</button>}</>}</Modal>}

function SettingsHome({state,close,setModal}){const p=state.profile,goal=p.useSuggested?tdee(p):p.goal;return <div className="settingsPage"><div className="settingsHead"><button onClick={close}>‹</button><div><h1>⚙ Settings</h1><p>Manage your profile and preferences</p></div></div><div className="settingsCard"><Setting title="Profile" icon="♙" value={p.name} onClick={()=>setModal({t:'profile'})}/><Setting title="Calorie Goal" icon="◎" value={`${goal} kcal`} onClick={()=>setModal({t:'goal'})}/><Setting title="Timezone" icon="◷" value="GMT+8 (Philippines)" onClick={()=>setModal({t:'timezone'})}/><Setting title="Saved Menus" icon="🍴" value="Manage" onClick={()=>setModal({t:'menus'})}/><Setting title="Hashtag" icon="#" value={p.hashtagMode==='manual'?p.manualHashtag:'Auto'} onClick={()=>setModal({t:'hashtag'})}/><Setting title="Colors" icon="◉" value={<span className="dots"><i style={{background:p.colors?.primary}}/><i style={{background:p.colors?.secondary}}/><i style={{background:p.colors?.foodButton}}/></span>} onClick={()=>setModal({t:'colors'})}/><button className="primary" onClick={close}>Save Settings</button></div></div>}
function Setting({title,icon,value,onClick}){return <button className="setting" onClick={onClick}><span className="settingIcon">{icon}</span><b>{title}</b><span>{value}</span><strong>›</strong></button>}
function back(setModal){setModal({t:'settings'})}
function Profile({state,up,setModal}){const[p,setP]=useState({...state.profile});return <Modal wide onClose={()=>back(setModal)}><h2>Profile</h2><label>Name<input value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></label><div className="two"><label>Height (cm)<input inputMode="numeric" value={p.heightCm} onChange={e=>setP({...p,heightCm:e.target.value.replace(/\D/g,'')})}/></label><label>Weight (kg)<input inputMode="numeric" value={p.weightKg} onChange={e=>setP({...p,weightKg:e.target.value.replace(/\D/g,'')})}/></label></div><label>Date of Birth<input type="date" value={p.dob} onChange={e=>setP({...p,dob:e.target.value})}/><small>Age: {age(p.dob)} years old</small></label><label>Gender<select value={p.gender} onChange={e=>setP({...p,gender:e.target.value})}><option value="male">Male</option><option value="female">Female</option></select></label><label>Activity Level<select value={p.activityLevel} onChange={e=>setP({...p,activityLevel:e.target.value})}><option value="sedentary">Sedentary</option><option value="light">Lightly Active</option><option value="moderate">Moderately Active</option><option value="very">Very Active</option><option value="extra">Extra Active</option></select></label><div className="calcBox">BMR: <b>{bmr(p)}</b> | TDEE: <b>{tdee(p)}</b> kcal/day</div><button className="primary" onClick={()=>{up(s=>({...s,profile:p}));back(setModal)}}>Done</button></Modal>}
function Goal({state,up,setModal}){const p=state.profile,[mode,setMode]=useState(p.useSuggested?'suggested':'custom'),[custom,setCustom]=useState(String(p.goal));return <Modal onClose={()=>back(setModal)}><h2>Calorie Goal</h2><label className={`choice ${mode==='suggested'?'selected':''}`}><input type="radio" checked={mode==='suggested'} onChange={()=>setMode('suggested')}/><div><b>Use Suggested <em>{tdee(p)} kcal</em></b></div></label><label className={`choice ${mode==='custom'?'selected':''}`}><input type="radio" checked={mode==='custom'} onChange={()=>setMode('custom')}/><div><b>Set Custom</b><input inputMode="numeric" value={custom} onChange={e=>setCustom(e.target.value.replace(/\D/g,''))}/></div></label><button className="primary" onClick={()=>{up(s=>({...s,profile:{...s.profile,useSuggested:mode==='suggested',goal:+custom||1800}}));back(setModal)}}>Done</button></Modal>}
function Timezone({state,up,setModal}){return <Modal onClose={()=>back(setModal)}><h2>Timezone</h2><select value={TZ} disabled><option value={TZ}>GMT+8 (Philippines/Singapore)</option></select><p className="muted">Used for daily calorie reset at midnight. Test v3 is fixed to Philippine time.</p><button className="primary" onClick={()=>{up(s=>({...s,profile:{...s.profile,timezone:TZ}}));back(setModal)}}>Done</button></Modal>}
function Menus({state,up,setModal}){const[adding,setAdding]=useState(false),[n,setN]=useState(''),[c,setC]=useState('');return <Modal wide onClose={()=>back(setModal)}><h2>Saved Menus</h2>{!adding?<button className="secondary" onClick={()=>setAdding(true)}>＋ Add New Dish</button>:<div className="menuAdd"><label>Dish Name<input value={n} onChange={e=>setN(e.target.value)}/></label><label>Default Calories<input inputMode="numeric" value={c} onChange={e=>setC(e.target.value.replace(/\D/g,''))}/></label><div className="two"><button className="secondary" onClick={()=>setAdding(false)}>Cancel</button><button className="primary" onClick={()=>{if(!n.trim()||!+c)return;up(s=>({...s,menus:[{id:uid(),name:n.trim(),cal:+c},...s.menus]}));setN('');setC('');setAdding(false)}}>Save</button></div></div>}<div className="list manage">{state.menus.map(x=><div key={x.id}><span><b>{x.name}</b><small>{x.cal} cal</small></span><button className="trash" onClick={()=>up(s=>({...s,menus:s.menus.filter(m=>m.id!==x.id)}))}>🗑</button></div>)}</div><button className="primary" onClick={()=>back(setModal)}>Done</button></Modal>}
function Hashtag({state,up,setModal}){const[p,setP]=useState({...state.profile});const today=HASHES[(+manilaParts().day-1)%HASHES.length];return <Modal onClose={()=>back(setModal)}><h2>App Hashtag</h2><label className={`choice ${p.hashtagMode==='auto'?'selected':''}`}><input type="radio" checked={p.hashtagMode==='auto'} onChange={()=>setP({...p,hashtagMode:'auto'})}/><div><b>Auto (Daily)</b><span>Changes daily, repeats monthly</span><em>Today: {today}</em></div></label><label className={`choice ${p.hashtagMode==='manual'?'selected':''}`}><input type="radio" checked={p.hashtagMode==='manual'} onChange={()=>setP({...p,hashtagMode:'manual'})}/><div><b>Manual</b><span>Set your own hashtag</span>{p.hashtagMode==='manual'&&<input value={p.manualHashtag} onChange={e=>setP({...p,manualHashtag:e.target.value.startsWith('#')?e.target.value:`#${e.target.value}`})}/>}</div></label><button className="primary" onClick={()=>{up(s=>({...s,profile:p}));back(setModal)}}>Done</button></Modal>}
function Colors({state,up,setModal}){const[c,setC]=useState({...DEFAULT_COLORS,...state.profile.colors});const labels={background:'Background',primary:'Primary',secondary:'Secondary',tabBackground:'Tab Background',textPrimary:'Text Primary',textSecondary:'Text Secondary',progressBar:'Progress Bar',foodButton:'Food Button',activityButton:'Activity Button'};return <Modal wide onClose={()=>back(setModal)}><h2>Display Colors</h2><div className="colorGrid">{Object.keys(labels).map(k=><label key={k}>{labels[k]}<div><input type="color" value={c[k]} onChange={e=>setC({...c,[k]:e.target.value})}/><input value={c[k]} onChange={e=>setC({...c,[k]:e.target.value})}/></div></label>)}</div><button className="secondary" onClick={()=>setC(DEFAULT_COLORS)}>Reset to Default</button><div className="two"><button className="secondary" onClick={()=>back(setModal)}>Cancel</button><button className="primary" onClick={()=>{up(s=>({...s,profile:{...s.profile,colors:c}}));back(setModal)}}>OK</button></div></Modal>}
